import type { Metadata } from 'next';

import { Wix_Madefor_Text } from 'next/font/google';
import { cookies } from 'next/headers';

import {
  DockPanel,
  Footer,
  GoogleTagManagerScript,
  Header,
  YandexMetrikaScript
} from './(components)';
import { getDictionary } from './(contexts)/intl/helpers/getDictionary';
import { Provider } from './provider';

import './globals.css';

const wixMadeforText = Wix_Madefor_Text({
  variable: '--font-wix-madefor-text',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const locale = 'ru';

const RootLayout = async ({ children }: Readonly<RootLayoutProps>) => {
  const cookieStore = await cookies();
  const theme = cookieStore.get('theme')?.value;
  const messages = await getDictionary(locale);

  return (
    <html className={theme} data-theme={theme} lang={locale}>
      <body className={`${wixMadeforText.variable}`}>
        {process.env.NODE_ENV === 'production' && (
          <>
            <YandexMetrikaScript />
            <GoogleTagManagerScript />
          </>
        )}

        <Provider intl={{ locale, messages }}>
          <Header />
          {children}
          <Footer />
          <div className='fixed right-0 bottom-5 left-0'>
            <DockPanel />
          </div>
        </Provider>
      </body>
    </html>
  );
};

export default RootLayout;
