import type { Metadata } from 'next';

import { Geist, Geist_Mono } from 'next/font/google';
import { cookies } from 'next/headers';

import {
  DockPanel,
  Footer,
  GoogleTagManagerScript,
  Header,
  YandexMetrikaScript
} from './(components)';
import { Provider } from './provider';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout = async ({ children }: Readonly<RootLayoutProps>) => {
  const cookieStore = await cookies();
  const theme = cookieStore.get('theme')?.value;

  return (
    <html className={theme} data-theme={theme}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <YandexMetrikaScript />
        <GoogleTagManagerScript />

        <Provider>
          <Header />
          <div className='mt-40'>{children}</div>
          <Footer />
          <div className='fixed right-0 bottom-5 left-0'>
            <DockPanel />
          </div>
        </Provider>
      </body>
    </html>
  );
};

export default RootLayout;
