export * from './AppleIcon';
export * from './FigmaIcon';
export * from './FrenchFries';
export * from './GithubIcon';
export * from './PizzaIcon';
export * from './RobotIcon';
export * from './TelegramIcon';
export * from './TestTubeIcon';
export * from './VkIcon';
